apiVersion: v1
kind: Service
metadata:
  name: midasmind-api-service
spec:
  type: LoadBalancer # 自動從雲端平台獲取外網 IP
  selector:
    app: midasmind-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080